### PR TITLE
Update to 2024

### PR DESCRIPTION
**Pull request by KangarooKoala**
`WPILib-License.md` was excluded from spotless since I felt better about including it verbatim, and `gradlew` was excluded from spotless since the `case` statements didn't format nicely.
Other than that, the changes were generated by using 2024 WPILib VSCode to create a new project (Java command template), copying all files into the repository, removing `src/java/frc/robot/*` and `src/deploy/example.txt`, and applying our custom changes to `build.gradle` and `settings.gradle` (testing support and adding spotless and errorprone). Notably, there were some custom changes to `.gitignore` that I dropped, since I wasn't sure if those still applied.

### CODE REVIEW

**Comment by KangarooKoala** [comment]
Running on my school laptop gets the same error as [the CI](https://github.com/robototes/Crescendo2024/actions/runs/7484488689/job/20371431704#step:4:21) about `org.gradle.api.tasks.compile.ForkOptions`.

**Comment by KangarooKoala** [comment]
The key fix was updating the `net.lgtg.errorprone` Gradle plugin for errorprone- Based on the error messages I got on my school laptop, it had been using 2.0.2, which was made for a much older version of Gradle, which led to a [`java.lang.InstantiationError`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/InstantiationError.html). However, while I was poking around, I went ahead and updated the core errorprone dependency and removed the unused jetbrains annotations dependency.

**Review by TAKBS2412 — APPROVED** [review]
LGTM, want to make sure that this will not conflict with the ongoing YAGSL work @jbko6

**Comment by jbko6** [comment]
think it'll be fine, I'll find out soon

**Pull request merged**
