### PR TITLE
Intake subsystem

### PR DESCRIPTION
**Pull request by eddiert1239**
added 3rd sensor
changed regular in commands to just return true for isfinished
when using all in command, the bottom intake motors stop after the indexsensor sees

### CODE REVIEW

**Comment by eddiert1239** [comment]
this is replacing the " ' " pr

**Review by TAKBS2412 — COMMENTED** [review]
Curious, what's the third sensor used for? I don't see it being used anywhere.

**Review by TAKBS2412 — COMMENTED** [review]
LGTM pending the response to my previous question.

**Comment by eddiert1239** [comment]
> Curious, what's the third sensor used for? I don't see it being used anywhere.

It isn't being used right now, I don't know what it would be used for but it is apparently on the robot. Should we remove it or implement it or what?

**Comment by TAKBS2412** [comment]
> > Curious, what's the third sensor used for? I don't see it being used anywhere.
> 
> It isn't being used right now, I don't know what it would be used for but it is apparently on the robot. Should we remove it or implement it or what?

If you're not sure what it would be used for, I'd say remove it, as it's not too hard to add it back later if we need to.

**Review by TAKBS2412 — APPROVED** [review]

**Pull request merged**
