### PR TITLE
Vendordeps updates

### PR DESCRIPTION
**Pull request by jbko6**

### CODE REVIEW

**Comment by jbko6** [comment]
Updates Phoenix v6, Revlib, and PathplannerLib

**Comment by KangarooKoala** [comment]
Out of curiosity, any particular reason for updating?

**Comment by jbko6** [comment]
No reason other than that I was already updating WPILib. This is not a priority if there are fears it will break other functionality (although from what I've seen it won't)

**Comment by jamesdooley4** [comment]
> Out of curiosity, any particular reason for updating?

I mentioned to Jonah that WPILib 2024.2.1 broke the playingwithfsusion vendor dep and required an update of their vendor dep at the same time as wpilib, so it might be good to double-check all our vendor deps and make sure they're up-to-date.

**Review by jamesdooley4 — APPROVED** [review]

**Comment by jamesdooley4** [comment]
FYI that here's the changelog for the RevLib update: https://github.com/REVrobotics/REV-Software-Binaries/releases/tag/revlib-2024.2.1
Most impactful for us:
> C++/Java: Changes behavior of SPARK Flex and MAX initialization errors to throw exceptions rather than terminating the robot program.

**Comment by jamesdooley4** [comment]
Phoenix changelog is here: https://api.ctr-electronics.com/changelog#20240209

**Pull request merged**
